CREATE TABLE IF NOT EXISTS vehicle_ownership (
  id INT AUTO_INCREMENT PRIMARY KEY,
  model VARCHAR(100) NOT NULL,
  plate VARCHAR(20) NOT NULL,
  vin VARCHAR(100) DEFAULT NULL,
  owner_id VARCHAR(100) NOT NULL,
  allowed_drivers TEXT DEFAULT NULL,
  imported_by VARCHAR(100) DEFAULT NULL,
  import_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  metadata TEXT DEFAULT NULL,
  UNIQUE KEY unique_plate (plate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;